Bug#38297776	Contribution: Fix postrm script to properly handle directory removal
- Check if /usr/lib/mysqlsh exists before attempting removal
- Verify rm command success and provide accurate feedback
- Send error messages to stderr with proper warning format
- Inform user when directory doesn't exist instead of silent operation

This patch contributed by EvgeniyPatlan <evgeniy.patlan@percona.com>

Change-Id: I24a62346bfdf83561100798eb3c8c5c159948a42

diff --git a/packaging/debian/postrm.in b/packaging/debian/postrm.in
--- a/packaging/debian/postrm.in
+++ b/packaging/debian/postrm.in
@@ -1,4 +1,4 @@
-# Copyright (c) 2022, 2024, Oracle and/or its affiliates.
+# Copyright (c) 2022, 2026, Oracle and/or its affiliates.
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License, version 2.0,
@@ -24,8 +24,15 @@
 set -e
 
 if [ "$1" = "purge" ]; then
-        rm -rf /usr/lib/mysqlsh 2>/dev/null
-        echo "Deleted /usr/lib/mysqlsh"
+    if [ -d "/usr/lib/mysqlsh" ]; then
+        if rm -rf /usr/lib/mysqlsh; then
+            echo "Successfully deleted /usr/lib/mysqlsh"
+        else
+            echo "Warning: Failed to delete /usr/lib/mysqlsh" >&2
+        fi
+    else
+        echo "Directory /usr/lib/mysqlsh does not exist, nothing to remove"
+    fi
 fi
 
 #DEBHELPER#
